### ISSUE TITLE
Prosím o radu

### ISSUE THREAD

**Issue by JitkaHo** [JitkaHo/PROJEKT-Cukrarna#1]
Ahoj Tome, 
pokusila jsem se nakódovat tu cukrárnu.
Nevím, jak dosáhnout podle zadání toho, aby hlavní obsah měl max-width: 1100px a od okrajů, aby bylo odsazení auto. 
Nevím, jakému elementu nastavit tu max-width, aby mi zůstal ten obrázek cupcakes a šedý pruh až do krajů.

A pak ještě se mi nedařilo, když by se nastavila ta max-width, tak aby se ta nabídka ty dortíky do toho vešly. 

Prosím o radu, děkuju
Jitka

**Comment by tommander** [comment]
<p>Ahoj Jitko, tak bídnu dvě rady, to by mělo pomoct ten úkol splnit :) Ještě mrknu, nejsou-li tam nějaké další drobnosti, ale nic tam v tuto chvíli nevidím, vypadá to s těmito dvěma "hacky" velmi dobře :)</p>
<ol>
  <li>V <code>div.hero</code> klidně můžeš mít vložený ještě jeden <code>div</code>, který bude mít omezenou šířku na 1100px, <code>margin 0 auto</code> a bude mít ten padding 40% zprava, jak to máš teď udělané. Tím se ti pak ten text správně srovná.</li>
  <li>U obrázků (cukrářka, dnešní nabídka, náš přístup) si přímo u těch prvků <code>img</code> nastav <code>max-width:100%</code>, tím se ty obrázky budou přizpůsobovat šířce toho kontejneru, ve kterém jsou.</li>
</ol>

**Comment by JitkaHo** [comment]
Ahoj Tome,
děkuju za "hacky", pomohlo to :)
Tak teď je to snad už dobrý.
Hezký víkend
Jitka
